backend:
  name: github
  repo: maasencioh/gff-frontend

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: description, label: Description }
      - { name: author, label: Author }
      - { name: body, label: Body, widget: markdown }
